version: '3'

services:

  db:
    container_name: quickstart_postgres
    hostname: pg.quickstart.com
    image: postgres:14-alpine
    environment:
      DATABASE_HOST: '127.0.0.1'
      PGUSER: 'postgres'
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "unidunite"

    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
      - ./docker/database:/docker-entrypoint-initdb.d
    networks:
      - quickstart 


networks:
  quickstart:
    driver: bridge